# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce23509991f0fac790049c6d70846615f9601234278e93c61bda5cf21066c02e794b9afc4245b4ed46194310c58fcf0aac8acaad85cadd35b570b890abfee29

test:
  secret_key_base: f9aaf7e275091854489bb0098d761afcb21351c5864bd007676666905652d865a36408ac044fdfcaf8d329a07ffb966dc947807164bf218d02997fafb7cbe963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
